vim.cmd("source ~/.config/nvim/plugins.vim")
vim.cmd("source ~/.config/nvim/rc.vim")

require("plugin.lsp")
require("plugin.compe")
require("plugin.kind")
require("plugin.format")
require("plugin.telescope")
require("plugin.treesitter")
require("plugin.indentline")
require("plugin.gitsign")
require("plugin.colorizer")
