vim.cmd('source ~/.config/nvim/plugins.vim')
require('global')
vim.cmd('source ~/.config/nvim/rc.vim')
-- vim.cmd('source ~/.config/nvim/coc.vim')

vim.cmd('source ~/.config/nvim/whichkey.vim')
require('colorscheme')
require('fuzzyfinder')
require('syntax')
require('indentline')
require('statusline')
require('gitsign')

require('formatter')
require('lsp.popup')
require('lsp.kind')
-- require('lsp.install')
require('lsp')
require('lsp.ts')
require('lsp.lua')
require('lsp.yaml')
require('lsp.json')
require('lsp.virtual_text')
require('lsp.go')
require('lsp.python')
require('lsp.bash')
